version: '3.8'
services: 
  mongodb:
    image: mongo:4.4.5
    container_name: db
    ports:
      - "27017:27017"
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    command: npm start
    ports:
      - "5000:5000"
    environment:
      PROCESS_TYPE: api
      PORT: 5000
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    depends_on: 
      - mongodb
